### ISSUE TITLE
Support GLPI 9.5

### ISSUE THREAD

**Issue by KongNan** [PR-gh/patchpanel#1]
Excellent plug-in!! It completely solves the corresponding problem between the switch and the panel!!
(https://forum.glpi-project.org/viewtopic.php?pid=360766#p360766)

The only problem now is that I installed GLPI9.5.1, and found that the plug-in can’t be used anymore. I hope the dev-team can  provide support for 9.5, thank you!

**Comment by GunFood** [comment]
change the following lines before activation: 
inc/patchpanel.class.php 
Line 37 from `use DCBreadcrumb;` to `use Glpi\Features\DCBreadcrumb;`
Line 57 from `$this->addDefaultFormTab($ong)` to `$this->addDefaultFormTab($ong, $options)`
Line 188 add `return true;` before the closing `}`

**Comment by KongNan** [comment]
Thank you GunFood ! Let me try

**Comment by KongNan** [comment]
It works, thank you GunFood!
